### ISSUE TITLE
Bug Upon Touching and releasing inactive button

### ISSUE THREAD

**Issue by cobyw** [cobyw/blocBrowser#1]
Edit: Not just inactive buttons, any button other than stop.

If you touch and release on an inactive button it crashes the app. I believe it has something to do with the touch handling in the colorful toolbar implementation file - lines 101 to 156, as follows
```
#pragma mark - Touch Handling

-(UILabel *)labelFromTouches:(NSSet *)touches withEvent:(UIEvent *)event
{
    UITouch *touch = [touches anyObject];
    CGPoint location = [touch locationInView:self];
    UIView *subview = [self hitTest:location withEvent:event];
    return (UILabel *)subview;
}

-(void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event
{
    UILabel *label = [self labelFromTouches:touches withEvent:event];
    
    self.currentLabel = label;
    self.currentLabel.alpha = 0.5;
    
    NSLog(@"Touch began on : %@", label.text);
}

-(void)touchesMoved:(NSSet *)touches withEvent:(UIEvent *)event
{
    UILabel *label = [self labelFromTouches:touches withEvent:event];
    
    if (self.currentLabel != label)//the label being touched is no longer the initial label
    {
        self.currentLabel.alpha = 1;
    }
    else //the label being touched is the initial label
    {
        self.currentLabel.alpha = 0.5;
    }
}

-(void)touchesEnded:(NSSet *)touches withEvent:(UIEvent *)event
{
    UILabel *label = [self labelFromTouches:touches withEvent:event];
    
    if (self.currentLabel == label)
    {
        NSLog(@"Label tapped: %@", self.currentLabel.text);
        
        if ([self.delegate respondsToSelector:@selector(floatingToolbar:didSelectButtonWithTitle:)])
        {
            [self.delegate floatingToolbar:self didSelectButtonWithTitle:self.currentLabel.text];
        }
    }
    self.currentLabel.alpha = 1;
    self.currentLabel = nil;
}

-(void) touchesCancelled:(NSSet *)touches withEvent:(UIEvent *)event
{
    self.currentLabel.alpha = 1;
    self.currentLabel = nil;
}
```

**Comment by laurenhasson** [comment]
Alright! A bug! So...

I think you are on to something here with it crashing on the touchesBegan:withEvent method - how do you think you could test to see if that is where the crash is occurring?

**Comment by cobyw** [comment]
By adding breaks and then going past them until it crashes.  The odd thing about it is all of that stuff is written exactly as they did.  I could have literally copy pasted it.

The issue I just found has to do with the uilabel.text, namely that the label doesnt have a text attribute as its looking at the whole colorfulToolbar instead of the individual buttons, the reason for this is unclear at the moment... though.

**Comment by laurenhasson** [comment]
What objects or subviews does the colorful toolbar show that it has 1) when it works and 2) when it crashes? what are the differences between the two?
— 
Lauren Hasson
214.864.4504 | lauren.r.hasson@gmail.com <mailto:lauren.r.hasson@gmail.com>
Connect with me on LinkedIn:
http://www.linkedin.com/in/laurenhasson <http://www.linkedin.com/in/laurenhasson>
